BEGIN TRANSACTION;

CREATE TABLE Songs (
	songID INTEGER PRIMARY KEY NOT NULL,
	songName TEXT NOT NULL
);

CREATE TABLE Venues (
	venueID INTEGER PRIMARY KEY NOT NULL,
	venueName TEXT NOT NULL,
	venueCity TEXT NOT NULL,
	venueState TEXT NOT NULL
);

CREATE TABLE Shows (
	showID INTEGER PRIMARY KEY NOT NULL,
	showDate DATE NOT NULL,
	venueID INTEGER NOT NULL,
	FOREIGN KEY (venueID) REFERENCES Venues (venueID)
);

CREATE TABLE Setlists (
	setlistEntry INTEGER PRIMARY KEY NOT NULL,
	showID INTEGER NOT NULL,
	SetNumber INTEGER NOT NULL,
	SetInfo TEXT NOT NULL,
	SongNumber INTEGER NOT NULL,
	SongID INTEGER NOT NULL,
	Segue BOOLEAN NOT NULL,
	Transition BOOLEAN NOT NULL,
	FOREIGN KEY (showID) REFERENCES Shows (showID),
	FOREIGN KEY (SongID) REFERENCES Songs (songID)
);

COMMIT;